apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    method: fromcode
  name: nginx-yaml
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - name: scratch-volume
          mountPath: /scratch
    - image: busybox
      name: busybox
      volumeMounts:
        - name: scratch-volume
          mountPath: /scratch
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi
